### ISSUE TITLE
App id not found

### ISSUE THREAD

**Issue by khrizzcristian** [vtex-apps/order-configuration#11]
I have an issue with this app. When I try to submit the form I receive the following error:

Request failed with status code 404

code: "1"
exception: null
message: "App id not found"

I have the masterdata schema created with your example. I didn't change anything 

![app_id](https://user-images.githubusercontent.com/43498488/111275139-81e07f80-863e-11eb-85ad-f03522e3fb0e.jpg)

**Comment by santosluiz000** [comment]
Hi @khrizzcristian. What workflow you're trying to do to config this app?

**Comment by khrizzcristian** [comment]
Hello. Well I followed the instructions from here: https://github.com/vtex-apps/order-configuration

And now I have that modal, i have the form, but when I try to submit the form I receive that error.

**Comment by gsasouza** [comment]
Hello @khrizzcristian, which version you are using?

**Comment by khrizzcristian** [comment]
I tried with 0.x first time and after that with 3.x. same result..

**Comment by gsasouza** [comment]
can you please share the workspace?

**Comment by khrizzcristian** [comment]
https://longo--mcxhoreca.myvtex.com/

You need to be logged in

email: cristian.longo@customsoft.ro
pass: Admin123!

**Comment by gsasouza** [comment]
can you please check the version of this app in your store-theme (mcxhoreca.b2b-store-theme@0.0.9) manifest?

**Comment by gsasouza** [comment]
We found a bug when using 3.x with custom-prices. If you want to use custom-prices with this app, please use version 2.x at this moment

**Comment by khrizzcristian** [comment]
This bug persist with 0.x also? Cuz i tried with that versions at the first time.

**Comment by gsasouza** [comment]
Yeah, sorry about that. The 0.x has a different bug that was fixed in 2.x version, and unfortunately, the 3.x is still incompatible with cutom-prices

**Comment by khrizzcristian** [comment]
I just tried with 2.x now and I get the same error. Maybe the schema structure is different?

**Comment by gsasouza** [comment]
hmmmm, it look likes your store theme is using 0.x
<img width="658" alt="image" src="https://user-images.githubusercontent.com/8701003/111815789-d6902e80-88ba-11eb-8717-08190671befd.png">

**Comment by gsasouza** [comment]
Please try to update it in your store-theme manifest

**Comment by khrizzcristian** [comment]
I did that in the morning on my workspace. I thing it's still linked

**Comment by gsasouza** [comment]
Where I can find in the page the order configuration popup?

**Comment by khrizzcristian** [comment]
You need to be logged in

email: cristian.longo@customsoft.ro
pass: Admin123!

**Comment by gsasouza** [comment]
I'm already in, but I didn't found order configurationbutton
<img width="1591" alt="image" src="https://user-images.githubusercontent.com/8701003/111819187-d42fd380-88be-11eb-988b-ce3e215a67d7.png">

**Comment by khrizzcristian** [comment]
https://longo--mcxhoreca.myvtex.com/

**Comment by khrizzcristian** [comment]
I'll check tomorrow. It seems my colleagues just made an update..

**Comment by gsasouza** [comment]
I'm in this workspace, but I don't understand romanian, so I'm trying to find where in the page is the order-configuration button

**Comment by khrizzcristian** [comment]
Done. You can find the Order configuration button in header. On that blue background.
https://longo--mcxhoreca.myvtex.com/

**Comment by gsasouza** [comment]
Thank you, I found the problem. Soon it will be fixed in your workspace

**Comment by khrizzcristian** [comment]
Great. please tell me if I can fix the problem on my own on master also

**Comment by gsasouza** [comment]
Sure, you just need to update to version 2.x and it should work. Sorry about that

**Comment by khrizzcristian** [comment]
Hello. Thank you
I can send the form now, but I have the question :)

Where can I find the stored data?
If I make a GET request on {{vendor}}.vtexcommercestable.com.br/api/dataentities/order_configuration/search/?_fields=_all&_schema=main

Returns me an empty array. No information seems to be saved in the master data
